### ISSUE TITLE
Can't view/dowload pictures

### ISSUE THREAD

**Issue by MRZA-MRZA** [noelnh/harbour-prxrv#1]
When I tap on a thumbinal general information about picture loads but not picture itself. I don't see it. When I select Download from pull down menue nothing happens. It doesn't add picture to download queue.

**Comment by joeysys** [comment]
Uploaded a new version 0.15.1

**Comment by MRZA-MRZA** [comment]
I updated Prxrv to the newest version on my AquaFish and Inoi. I can view pictures now (but in small size) but can't download. When I select Download it does nothing :(

**Comment by noelnh** [comment]
New version 0.16.0 

If not work:
1. Re-check your downloads settings
2. Enable debug mode, then start from command line: `harbour-prxrv` or save log to a file `harbour-prxrv &> logfile`

**Comment by MRZA-MRZA** [comment]
It works properly now. Thank you!
